### ISSUE TITLE
⚠️  Is this a fork or?

### ISSUE THREAD

**Issue by loneicewolf** [BadrBenSlama/Stuxnet-Source-main#1]

**Comment by loneicewolf** [comment]
because it looks like it is a replica of [my repo](https://github.com/loneicewolf/Stuxnet-Source)?

**Comment by BadrBenSlama** [comment]
> 

yes, is that a problem?

**Comment by loneicewolf** [comment]
note: this issue is "not an issue" or "offense" Just wanted to make sure; since if this is meant to be a fork - it won't be updated :) Just saying;


have a great day! //Will.
